backend/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("currency.urls")),
]

backend/currency/urls.py
from django.urls import path

from . import views

app_name = "currency"

urlpatterns = [
    path("", views.CurrencyView.as_view(), name="currency_view_form"),
    path("currencies/", views.CurrencyAPI.as_view(), name="currencies"),
]

backend/currency/models.py
from django.db import models


class CurrencyName(models.Model):
    name = models.CharField(max_length=40)
    code = models.CharField(max_length=3)

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = "Currency names"
        verbose_name_plural = "Currency name"


class CurrencyDate(models.Model):
    date = models.DateField(db_index=True, unique=True)

    def __str__(self):
        return str(self.date)

    class Meta:
        verbose_name = "Currency date"
        verbose_name_plural = "Currency dates"


class CurrencyValue(models.Model):
    exchange_rate = models.DecimalField(max_digits=10, decimal_places=8)
    currency_name = models.ForeignKey("CurrencyName", on_delete=models.CASCADE, related_name="currency_values")
    currency_date = models.ForeignKey("CurrencyDate", on_delete=models.CASCADE, related_name="currency_values")

    def __str__(self):
        return str(self.exchange_rate)

    class Meta:
        verbose_name = "Currency value"
        verbose_name_plural = "Currency values"
        unique_together = ("currency_name", "currency_date")

backend/users/models.py
from django.contrib.auth.models import AbstractUser


# Create your models here.
class CustomUser(AbstractUser):
    pass

backend/currency/forms.py
from django import forms


class CurrencyForm(forms.Form):
    start_date = forms.DateField(widget=forms.TextInput(attrs={"type": "date"}))
    end_date = forms.DateField(widget=forms.TextInput(attrs={"type": "date"}))
    currency = forms.MultipleChoiceField(choices=[], widget=forms.CheckboxSelectMultiple)

backend/currency/views.py
import json
from datetime import datetime, timedelta
from urllib import request

from django.views.generic import FormView
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from currency.forms import CurrencyForm
from currency.models import CurrencyName, CurrencyDate, CurrencyValue
from currency.serializers import CurrencyRateSerializer


def get_holidays(start_date, end_date):
    start_date = datetime.strftime(start_date, "%Y-%m-%d")
    end_date = datetime.strftime(end_date, "%Y-%m-%d")
    url = f"https://openholidaysapi.org/PublicHolidays?countryIsoCode=PL&languageIsoCode=PL&validFrom={start_date}&validTo={end_date}"
    with request.urlopen(url) as response:
        data = json.loads(response.read().decode())

    return [holiday["startDate"] for holiday in data]


def count_days_off(start_date, end_date):
    days_count = 0
    while start_date <= end_date:
        if start_date.weekday() >= 5:
            days_count += 1

        start_date += timedelta(days=1)
    return days_count


def count_holidays_during_weekends(start_date, end_date):
    holidays = get_holidays(start_date, end_date)
    count_weekday_holidays = 0

    for holiday in holidays:
        if datetime.strptime(holiday, "%Y-%m-%d").weekday() < 5:
            count_weekday_holidays += 1

    return count_weekday_holidays


def count_days(start_date, end_date):
    return (end_date - start_date).days


def get_currency_data_from_nbp_api(start_date, end_date):
    currency_nbp_url = f"http://api.nbp.pl/api/exchangerates/tables/A/{start_date}/{end_date}/"
    with request.urlopen(currency_nbp_url) as response:
        data = json.loads(response.read().decode())

    currency_names = CurrencyName.objects.all()

    for day in data:
        if not CurrencyDate.objects.filter(date=day["effectiveDate"]):
            currency_date = CurrencyDate.objects.create(date=day["effectiveDate"])
            currency_values = [
                CurrencyValue(
                    exchange_rate=rate["mid"],
                    currency_name=currency_names.get(code=rate["code"]),
                    currency_date=currency_date,
                )
                for rate in day["rates"]
            ]
            CurrencyValue.objects.bulk_create(currency_values)


class CurrencyView(FormView):
    form_class = CurrencyForm
    template_name = "currency/currency_form_view.html"
    success_url = "/"

    def get_form(self, form_class=None):
        currencies = CurrencyName.objects.all()
        form = super().get_form(form_class)

        form.fields["currency"].choices = [(currency.code, currency.name.title()) for currency in currencies]

        return form


class CurrencyAPI(APIView):
    def post(self, request, format=None):
        start_date = request.data.get("start_date")
        end_date = request.data.get("end_date")

        if start_date is not None and end_date is not None:
            start_date = datetime.strptime(start_date, "%Y-%m-%d")
            end_date = datetime.strptime(end_date, "%Y-%m-%d")
            currencies = CurrencyName.objects.all()

            dates = CurrencyDate.objects.filter(date__range=(start_date, end_date))

            if dates.count() < count_days(start_date, end_date) - count_holidays_during_weekends(
                start_date, end_date
            ) - count_days_off(start_date, end_date):
                get_currency_data_from_nbp_api(start_date, end_date)

            currency_data = CurrencyValue.objects.filter(
                currency_date__date__range=(start_date, end_date)
            ).select_related("currency_name")

            data = {
                "labels": [str(date) for date in dates],
                "datasets": [
                    {
                        "label": currency.code,
                        "data": [
                            float(value.exchange_rate)
                            for value in currency_data
                            if value.currency_name.code == currency.code
                        ],
                    }
                    for currency in currencies
                ],
            }
        else:
            return Response("Start date and end date required.", status=status.HTTP_400_BAD_REQUEST)

        return Response(data=data, status=status.HTTP_200_OK)

backend/currency/templates/currency/currency_form_view.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

</head>
<body>
<form action="" method="POST" id="currencyForm">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Submit</button>

</form>
<div style="width: 800px;">
    <canvas id="currencyChart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
let responseData = null; // Zmienna do przechowywania danych odpowiedzi

// Funkcja do inicjacji początkowego wykresu
function initializeChart() {
    return new Chart(
        document.getElementById('currencyChart'),
        {
            type: 'line',
            data: {
                labels: [], // Początkowo puste etykiety (daty)
                datasets: [] // Początkowo pusty wykres
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: true,
                        text: 'Currency exchange rate'
                    }
                },
                scales: {
                    y: {
                        min: 0,
                        max: 7,
                        ticks: {
                            stepSize: 0.01
                        },
                    }
                }
            },
        }
    );
}

// Inicjacja początkowego wykresu
let currencyChart = initializeChart();

// Funkcja do aktualizacji wykresu na podstawie zaznaczonych walut i danych
function updateChart(selectedCurrencies, data) {
    // Ustalamy jedną wspólną listę etykiet (daty)
    const labels = data.labels;

    // Zainicjuj puste zestawy danych
    const datasets = [];

    // Przetwórz dane dla każdej zaznaczonej waluty
    selectedCurrencies.forEach(currencyCode => {
        const currencyData = data.datasets.find(dataset => dataset.label === currencyCode);

        if (currencyData) {
            // Dodaj zestaw danych
            datasets.push({
                label: currencyCode,
                data: currencyData.data,
                borderColor: getRandomColor(),
                fill: false
            });
        }
    });

    // Aktualizuj dane wykresu
    currencyChart.data.labels = labels;
    currencyChart.data.datasets = datasets;
    currencyChart.update();
}

// Funkcja do pobierania zaznaczonych walut i aktualizacji wykresu
function handleCheckboxChange() {
    const selectedCurrencies = getSelectedCurrencies();
    if (responseData) {
        // Aktualizuj wykres na podstawie zaznaczonych walut i danych
        updateChart(selectedCurrencies, responseData);
    }
}

// Funkcja do pobierania zaznaczonych walut
function getSelectedCurrencies() {
    const checkboxes = document.querySelectorAll('input[name="currency"]');
    const selectedCurrencies = Array.from(checkboxes)
        .filter(checkbox => checkbox.checked)
        .map(checkbox => checkbox.value);
    return selectedCurrencies;
}

// Funkcja do generowania losowego koloru
function getRandomColor() {
    const letters = '0123456789ABCDEF';
    let color = '#';
    for (let i = 0; i < 6; i++) {
        color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
}

// Nasłuchuj zdarzenia zmiany zaznaczenia checkboxa
const checkboxes = document.querySelectorAll('input[name="currency"]');
checkboxes.forEach(checkbox => {
    checkbox.addEventListener('change', () => {
        handleCheckboxChange();
    });
});

// Obsługa wysłania formularza i pobrania danych
const form = document.querySelector("#currencyForm");
form.addEventListener("submit", async (event) => {
    event.preventDefault();

    const startDateInput = document.querySelector("#id_start_date");
    const endDateInput = document.querySelector("#id_end_date");

    try {
        const response = await fetch('/currencies/', {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                'start_date': startDateInput.value,
                'end_date': endDateInput.value,
                'currencies': getSelectedCurrencies()
            })
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        responseData = await response.json(); // Zapisz dane odpowiedzi

        // Aktualizuj wykres na podstawie danych odpowiedzi
        if (responseData) {
            updateChart(getSelectedCurrencies(), responseData);
        }
    } catch (error) {
        console.error('Wystąpił błąd podczas pobierania lub renderowania danych:', error);
    }
});


</script>
</body>
</html>